### ISSUE TITLE
 UI-Elemente verschoben bzw. teilweise nicht sichtbar (Widescreen-Auflösung)

### ISSUE THREAD

**Issue by theYeshir** [Apoc-/MasterThesisPrototype#11]
Auflösung ist 2560x1080

Logo abgeschnitten
![Logo](https://user-images.githubusercontent.com/61141908/74643591-45a9c980-5175-11ea-8687-60aadad3f128.png)

UI-Elemente verschoben
![UI-Elemente](https://user-images.githubusercontent.com/61141908/74643582-3fb3e880-5175-11ea-966c-5f9cf25046da.png)

**Comment by lordigquest** [comment]
Würde aus Zeitgrüden empfehlen, die Auflösung auf nicht! widescreen zu beschränken

**Comment by theYeshir** [comment]
Ist ja Widescreen ;) very wide screen

**Comment by lordigquest** [comment]
Ja, hab mich verschrieben, meine natürlich nicht wide screen

**Comment by Apoc-** [comment]
Sollte eigentlich bereits so eingestellt sein, aber muss ich wohl nochmal prüfen.
