### ISSUE TITLE
Reparatur scheint länger zu dauern als dass die leute das Gerät benutzen

### ISSUE THREAD

**Issue by lordigquest** [Apoc-/MasterThesisPrototype#13]
Es wirkt irgendwie unfär, wenn man schon am reparieren ist, dass die leute hingehen und sich ärgern, dass das Gerät nicht geht.

**Comment by Apoc-** [comment]
Ja, die Zeit ist aktuell gleich, werde die "Reparaturzeit" vermutlich reduzieren, sodass deine Situation seltener vorkommt

**Comment by Apoc-** [comment]
Done
