### ISSUE TITLE
Ich schicke Person zum Daily Meeting und es wird gesagt, es waren nicht alle im daily

### ISSUE THREAD

**Issue by lordigquest** [Apoc-/MasterThesisPrototype#20]
Selbes Problem wie beim Reparieren. Es wirkt unfair, dass Personen, die eigentlich schon zum Daily gehen negativ ausgelegt werden.

**Comment by theYeshir** [comment]
Ja, ich fand auch den Zeitraum zum rumschicken der Personen sehr eng begrenzt, ich hatte alle hingeschickt und sie waren auf dem Weg, aber waren halt noch nicht da und es gab negative Konsequenzen
