### ISSUE TITLE
Ideen für Scum Master Tätigkeiten

### ISSUE THREAD

**Issue by theYeshir** [Apoc-/MasterThesisPrototype#22]
- Streit schlichten 
- Telefonat mit Stakeholdern
- Retrospektive abhalten
- neue Methoden raussuchen
- Einzelgespräche
- Teambuilding
Wenn auch ironisch lustig gewünscht:
- Post-its sortieren
- Pokerkarten mischen (Planning Poker)
- Smilies auf Whiteboard malen

Wenn mir noch mehr einfällt, dann schreibe ich es rein

**Comment by Apoc-** [comment]
Gibt jetzt noch nen Wasserspender UND telefonate
