### ISSUE TITLE
Kann Leute zum Meeting schicken, obwohl Meeting vorbei

### ISSUE THREAD

**Issue by theYeshir** [Apoc-/MasterThesisPrototype#24]
Führt dazu, dass Leute vorm Meetingraum eingefroren sind...

![image](https://user-images.githubusercontent.com/61141908/74645406-282a2f00-5178-11ea-90ba-1dba834e8edd.png)

Muss ich noch weiter untersuchen um es zu reproduzieren

**Comment by theYeshir** [comment]
Dritter Tag(Nach Test-Nachricht) ->Niemanden zum Meeting schicken -> Aktion bleibt bei den Leuten verfügbar -> Leute bleiben vorm Raum stehen und machen nix mehr
Reproduzierbar!

**Comment by theYeshir** [comment]
Alle bis auf Joe sind schickbar...

**Comment by theYeshir** [comment]
Es werden sogar Punkte für die Aktion gut geschrieben

**Comment by Apoc-** [comment]
Am Tag nach der Test Nachricht gibt es undefiniertes Verhalten, da das Spiel zuvor bereits beendet sein sollte.

Es wird einen End Screen geben, von dem aus man das Spiel dann beenden kann.
