### ISSUE TITLE
Beim Taskboard ist immer der letzte Task nicht richtig eingeordnet

### ISSUE THREAD

**Issue by lordigquest** [Apoc-/MasterThesisPrototype#28]
Sobald es was falsch ist, muss man nur den letzen Task ins Doing schieben.

**Comment by Apoc-** [comment]
Es liegt in der Natur der Sache, dass, wenn überhaupt, immer der als letztes hinzugefügte Task fehlerhaft ist.

Wenn du etwas anderes meinst: Kannst du das nochmal genauer ausführen?

**Comment by Apoc-** [comment]
Ist jetzt komplexer
