### ISSUE TITLE
Scrum master muss am daily meeting nicht teilnehmen

### ISSUE THREAD

**Issue by M-tt** [Apoc-/MasterThesisPrototype#4]
Spieler muss nicht selbst zum besprechungszimmer, wenn das daily meeting stattfindet

ist das absicht?

**Comment by theYeshir** [comment]
Scrum Master müssen auch nicht unbedingt an daily scrums teilnehmen, wird aber manchmal empfohlen (Hängt von der Auslastung des Scrum Masters ab...)

**Comment by Apoc-** [comment]
Siehe Yeshir's Kommentar, werde das vorerst so lassen, insbesondere wenn der Spieler in Zukunft noch mehr außerhalb zu tun bekommt.
