### ISSUE TITLE
Agile principle animation flash

### ISSUE THREAD

**Issue by M-tt** [Apoc-/MasterThesisPrototype#5]
wenn der bildschirm zum 2. mal kommt, sieht man 1 frame lang den spruch in der mitte aufblitzen, und anschließend einfliegen

animation wird wahrscheinlich 1 frame  zu spät zurückgesetzt

**Comment by Apoc-** [comment]
Sieht jetzt ganz ok aus, bin mir aber nicht sicher ob es endgültig gefixed ist, werde aber auch nichtsmehr dran machen.
