### ISSUE TITLE
Intro - Rechtschreibfehler

### ISSUE THREAD

**Issue by Mijago** [Apoc-/MasterThesisPrototype#61]
![image](https://user-images.githubusercontent.com/3903469/75188290-2bab5080-574c-11ea-92e9-d3c808712e5f.png)

Das adjektiv sollte klein sein: "Je **agiler** das Team ist ...".
Natürlich könnte man hier argumentieren, dass es sich um eine Referenz auf "Agile" handelt, dennoch würde ich es klein schreiben.

**Comment by theYeshir** [comment]
![image](https://user-images.githubusercontent.com/61141908/75334659-86e25d80-5888-11ea-92ef-9021c681d513.png)

Erstes sollte groß sein ;) https://www.korrekturen.de/wortliste/als_erstes.shtml
