### ISSUE TITLE
Hohe Auslastung

### ISSUE THREAD

**Issue by Mijago** [Apoc-/MasterThesisPrototype#65]
Das Spiel bringt meine Grafikkarte (NVidia 2070 Super) auf über 90% Belastung, die CPU auf 20% (also einen Kern auf 60%) und das permanent (selbst wenn herausgetabbt).

Selbst die meisten AAA Titel möchten nicht so viel Leistung und ich sehe nichts im Spiel, das so viel Grafikleistung benötigen würde.

**Comment by Mijago** [comment]
![image](https://user-images.githubusercontent.com/3903469/75189391-5ac2c180-574e-11ea-8b7c-d74af651edaf.png)

**Comment by Mijago** [comment]
Dann, als das Spiel ausgeschaltet wurde:
![image](https://user-images.githubusercontent.com/3903469/75190426-8d6db980-5750-11ea-801a-9b7c43e2b0fd.png)

**Comment by M-tt** [comment]
🤷‍♂ 
![SharedScreenshot](https://user-images.githubusercontent.com/20758881/75193854-5ea71180-5757-11ea-9add-62de347bb383.jpg)

**Comment by theYeshir** [comment]
![image](https://user-images.githubusercontent.com/61141908/75334998-138d1b80-5889-11ea-928d-363c5e6841ef.png)

**Comment by Apoc-** [comment]
Problem gefunden: Bei Alex is das Spiel mit 244hz gelaufen, weil er es hald kann :D.

Framerate ist jetzt auf 60FPS gecapped.
