### ISSUE TITLE
Berater nach Tag 2 - Komma

### ISSUE THREAD

**Issue by Mijago** [Apoc-/MasterThesisPrototype#66]
![image](https://user-images.githubusercontent.com/3903469/75189721-1683f100-574f-11ea-9001-b40dfa562cd1.png)
Die beiden Sätze bitte mal durch den Gitty-Filter werfen.

**Comment by Mijago** [comment]
![image](https://user-images.githubusercontent.com/3903469/75189863-6a8ed580-574f-11ea-9f05-7ea737f07857.png)
Hier auch

**Comment by Apoc-** [comment]
Das Komma nach "endlich" gehört nicht hin, sondern VOR das "endlich",  ich vermute mal das ist dir verrutscht.
