### ISSUE TITLE
play/pause durch leertaste toggelt nich trichtig

### ISSUE THREAD

**Issue by M-tt** [Apoc-/MasterThesisPrototype#72]
wenn ich einmal mit der maus oben pausiere und dann leertaste drücke wird nochmal pausiert, erneutes betätigen der leertaste lässt das spiel wieder weiterlaufen

das gleiche gilt auch andersherum, also mit leertaste pausieren und dann mit maus weiterlaufen lassen => leertaste lässt ein zweites mal weiterlaufen

**Comment by Apoc-** [comment]
Jo, das war, weil er das als Button im Rahmen der Tastaturnavigation in Menüs markiert hatte. Somit konnte man mit Space den Button betätigen UND es wurde nochmal über den KeyCode von Space Pause getoggelt.
