### ISSUE TITLE
Zwei Fehler auf dem Taskboard gleichzeitig macht es permanent kaputt

### ISSUE THREAD

**Issue by untalentet** [Apoc-/MasterThesisPrototype#74]
Es sind zwei Leute zum Taskboard gegangen und bei beiden wurde ich alarmiert das ein Fehler auf dem Brett ist. Ich habe dann einen Fehler behoben, es war nichts mehr falsch, aber das Taskboard galt den Rest des Tages als falsch angeordnet und hat meine Produktivität runter gesetzt.

**Comment by Apoc-** [comment]
Ist kein Bug, sondern es war nur nicht ganz klar wie die Mechanik funktioniert, werde versuchen das ein wenig besser zu erklären.
