### ISSUE TITLE
Arbeitssicherheitseinführung: Tag 1 aus Screenshot

### ISSUE THREAD

**Issue by theYeshir** [Apoc-/MasterThesisPrototype#85]
![image](https://user-images.githubusercontent.com/61141908/75622264-c964ac80-5b9e-11ea-8f1e-47b3d8c349d4.png)
 
![image](https://user-images.githubusercontent.com/61141908/75622288-f2853d00-5b9e-11ea-982e-3b7d16a8822e.png)

Oder steht da an der Wand immer Tag 1? ;)

**Comment by Apoc-** [comment]
Issn Screenshot, da steht immer Tag 1 im Tutorial. Bleibt so =).
