### ISSUE TITLE
Anruf: Überschneidung von UI-Elementen

### ISSUE THREAD

**Issue by theYeshir** [Apoc-/MasterThesisPrototype#88]
![image](https://user-images.githubusercontent.com/61141908/75622459-c66abb80-5ba0-11ea-8ae7-ca30d9f74528.png)
 
Kann auch Absicht sein, aber ich dachte ich schreibe es einfach nochmal auf.
Das Fenster wird schon sehr schnell größer...

**Comment by Apoc-** [comment]
Ist kein Bug.
